title: Job Service
email: caf@hpe.com

description: Job Service Documentation
baseurl: "https://pages.github.hpe.com/caf/job-service"

# Build settings
exclude: ['node_modules']

markdown: kramdown
highlighter: rouge

gems: ['jekyll-coffeescript', 'jekyll-watch', 'jekyll-assets', 'jekyll-paginate']

layouts_dir:  caf-templates/_layouts
includes_dir: caf-templates/_includes

paginate: 5
paginate_path: "/pages/en-us/blog/page:num/"

sass:
    sass_dir: caf-templates/_sass
