title: Worker Framework
email: workerframework@microfocus.com

description: Worker Framework Documentation
baseurl: "/worker-framework"

navigation_image: 'assets/img/worker-framework-logo.png'

custom_stylesheet: 'assets/css/site.css'

# Build settings
exclude: ['node_modules']

markdown: kramdown
highlighter: rouge

gems: ['jekyll-coffeescript', 'jekyll-watch', 'jekyll-assets', 'jekyll-paginate']

layouts_dir:  caf-templates/_layouts
includes_dir: caf-templates/_includes

paginate: 5
paginate_path: "/pages/en-us/blog/page:num/"

sass:
    sass_dir: caf-templates/_sass
